version: 0.1
            
phases:
  
  install:
    commands:
      - sudo apt-get -qq update
      - sudo apt-get -qq install apt-transport-https
      - sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -qq update
      - sudo apt-get -qq install -y yarn
  
  pre_build:
    commands:
      - sudo yarn install
  
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: .